stages:
  - init
  - rpmbuild
  - prepare-rhel-internal
  - test
  - cleanup
  - finish

.base:
  after_script:
    - schutzbot/update_github_status.sh update
    - schutzbot/save_journal.sh
    - schutzbot/run_cloud_cleaner.sh
  tags:
    - terraform
  artifacts:
    paths:
      - journal-log.gpg
      - ci-artifacts
    when: always

.terraform:
  extends: .base
  tags:
    - terraform

.terraform/openstack:
  extends: .base
  tags:
    - terraform/openstack


init:
  stage: init
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start
  interruptible: true

RPM:
  stage: rpmbuild
  extends: .terraform
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - sh "schutzbot/mockbuild.sh"
  interruptible: true
  after_script:
    - schutzbot/update_github_status.sh update
    - schutzbot/save_journal.sh
  artifacts:
    paths:
      - journal-log.gpg
    when: always
  parallel:
    matrix:
      - RUNNER:
          - aws/centos-stream-8-x86_64
        INTERNAL_NETWORK: ["true"]

Container:
  stage: rpmbuild
  extends: .terraform
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - sh "schutzbot/containerbuild.sh"
  interruptible: true
  parallel:
    matrix:
      - RUNNER:
          - aws/centos-stream-8-x86_64


New OSTree:
  stage: test
  extends: .terraform/openstack
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $RUNNER =~ /[\S]+rhel-9.0-[^ga][\S]+/ && $NIGHTLY == "true" && $RHEL_MAJOR == "9"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $RUNNER =~ /[\S]+rhel-8.6-[^ga][\S]+/ && $NIGHTLY == "true" && $RHEL_MAJOR == "8"'
  script:
    - schutzbot/deploy.sh
    - /usr/libexec/tests/osbuild-composer/ostree-ng.sh
  interruptible: true
  parallel:
    matrix:
      - RUNNER:
          - rhos-01/centos-stream-8-x86_64


finish:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
