stages:
  - init
  - rpmbuild
  - prepare-rhel-internal
  - test
  - cleanup
  - finish

.base:
  after_script:
    - schutzbot/update_github_status.sh update
#     - schutzbot/save_journal.sh
    - schutzbot/run_cloud_cleaner.sh
  tags:
    - terraform
  artifacts:
    paths:
      # - journal-log
      - ci-artifacts
    when: always

.terraform:
  extends: .base
  tags:
    - terraform

.terraform/openstack:
  extends: .base
  tags:
    - terraform/openstack

init:
  stage: init
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

Test Load Test:
  stage: test
  extends: .terraform
  script:
    - schutzbot/ci_details.sh
    - test/cases/load_test.sh
  parallel:
    matrix:
      - RUNNER:
          - aws/rhel-8.4-ga-x86_64
        INTERNAL_NETWORK: ["true"]


finish:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
